name: Run Scrape Script

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    concurrency:
      group: scrape-script

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install web-push

    - name: Run scrape script
      run: python scrape.py

    - name: Check for changes in data.csv
      run: |
        if git diff --name-only | grep -q "data.csv"; then
          echo "data_changed=true" >> $GITHUB_ENV
        else
          echo "data_changed=false" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.data_changed == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.csv
        git commit -m "Update data.csv with new items" || echo "No changes to commit"
        git push

    - name: Send Push Notification
      if: env.data_changed == 'true'
      run: node notify.js
      env:
        VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
        VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
        PUSH_SUBSCRIPTION: ${{ secrets.PUSH_SUBSCRIPTION }}
        CONTACT_EMAIL_ADDRESS: ${{ secrets.CONTACT_EMAIL_ADDRESS }}
